### ISSUE TITLE
Bump slang to the latest version

### ISSUE THREAD

**Issue by SpriteOvO** [vivekmalneedi/veridian#194]
Are there any plans to bump slang to the latest version? I'm interested in working on it.

slang no longer provides pre-compiled binaries since v1.0, and bumping means we need to either compile it ourselves in `build.rs`, or manually install it by the user. Which way do you prefer?

**Comment by vivekmalneedi** [comment]
That's unfortunate, but I think compiling it ourselves in build.rs is better.
I just tried building it and it worked but I had to add `-DSLANG_USE_MIMALLOC=OFF` since it couldn't find mimalloc for some reason.
Feel free to take a shot at it and let me know if you run into any issues.
