### ISSUE TITLE
dot completion not showing correct data 

### ISSUE THREAD

**Issue by zegervdv** [vivekmalneedi/veridian#25]
I'm trying to get the dot completion working like in the asciinema example, but I am getting strange results.

Test case:

``` systemverilog
interface simple_bus (
    input logic clk
);
  logic req;
  modport slave(input req);
endinterface

module test;
  logic clk;
  simple_bus bus(.  // <-- completing here
endmodule
```

The only completion option veridian is giving me is ` simple_bus Interface interface`.

I am using the nvim builtin LSP with completion-nvim plugin, so I may just have a wrong setting here.

I am on version 97ba4a3d6677e2175788a5b9b1dd572af104ed92

**Comment by vivekmalneedi** [comment]
According to the docs the nvim builtin LSP client doesn't yet support completion context, which is what I was using to check if completion was triggering off of a trigger character like period, dollar sign, or backtick.
Fortunately the workaround isn't complicated and the latest nightly release should have this working.

**Comment by zegervdv** [comment]
Awesome! Thanks for the quick reply and fix :)
